web/router.ex
defmodule Datjournaal.Router do
  use Datjournaal.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :with_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug Datjournaal.CurrentUser
  end

  pipeline :login_required do
    plug Guardian.Plug.EnsureAuthenticated,
         handler: Datjournaal.GuardianErrorHandler
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
  end

  scope "/", Datjournaal do
    pipe_through [:browser, :with_session]

    get "/", IndexController, :index
    resources "/sessions", SessionController, only: [:new, :create, :delete]

    scope "/" do
      pipe_through [:login_required]
      resources "/posts", ImagePostController, only: [:create, :delete, :new]
      resources "/settings", UserSettingsController, only: [:index, :delete]
      resources "/stats", UserStatsController, only: [:index]
      resources "/text_posts", TextPostController, only: [:new, :edit, :create, :delete, :update]
      get "/auth/request", TwitterAuthController, :request
      get "/auth/callback", TwitterAuthController, :callback
      get "/auth/logout", TwitterAuthController, :logout
    end
    get "/about", StaticPagesController, :about
    get "/texts/:slug", IndexController, :show_text
    get "/images/:slug", IndexController, :show_image
    get "/:slug", IndexController, :show_legacy #This has to be the last route in the file because it acts as a catch-all
  end
  # Other scopes may use custom stacks.
  scope "/api", Datjournaal do
    pipe_through [:api]
    scope "/" do
      pipe_through [:with_session]
      scope "v1" do
        pipe_through [:login_required]
        get "/location", LocationController, :get_location_for_name
      end
      scope "v1" do
        post "/visit/image/:id", TrackingController, :log_image_visit
        post "/visit/text/:id", TrackingController, :log_text_visit
      end
    end
  end
end

web/views/layout_view.ex
defmodule Datjournaal.LayoutView do
  use Datjournaal.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Jan Schulte">

    <title>Dat Journaal</title>
    <link href="https://fonts.googleapis.com/css?family=Sorts+Mill+Goudy|Roboto|Dancing+Script:700" rel="stylesheet">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <header class="header">
      <nav role="navigation">
        <%= link "Dat Journaal", to: index_path(@conn, :index), class: "logo" %>
        <%= link "About", to: static_pages_path(@conn, :about) %>
      </nav>
    </header>
    <%
      info = get_flash(@conn, :info)
      error = get_flash(@conn, :error)
    %>

    <%= if info do %>
      <p class="alert alert-info" role="alert"><%= info %></p>
    <% end %>
    <%= if error do %>
      <p class="alert alert-danger" role="alert"><%= error %></p>
    <% end %>

    <main role="main" class="main">
      <%= render @view_module, @view_template, assigns %>
    </main>

    <footer class="footer">
      <ul class="list-inline menu">
        <%= if @current_user do %>
          <li>
            <%= link to: image_post_path(@conn, :new) do %>
              <i class="fa fa-picture-o" aria-hidden="true"></i>
            <% end %>
          </li>
          <li>
            <%= link to: text_post_path(@conn, :new) do %>
              <i class="fa fa-plus" aria-hidden="true"></i>
            <% end %>
          </li>
          <li>
            <%= link to: user_settings_path(@conn, :index) do %>
              <i class="fa fa-sliders" aria-hidden="true"></i>
            <% end %>
          </li>
          <li>
            <%= link to: user_stats_path(@conn, :index) do %>
              <i class="fa fa-line-chart" aria-hidden="true"></i>
            <% end %>
          </li>
          <li>
            <%= button to: session_path(@conn, :delete, @current_user), method: :delete do %>
              <i class="fa fa-sign-out" aria-hidden="true"></i>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link to: session_path(@conn, :new) do %>
              <i class="fa fa-sign-in" aria-hidden="true"></i>
            <% end %>
          </li>
        <% end %>
      </ul>
    </footer>
    <script src="<%= static_path(@conn, "/js/phoenix.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>