web/router.ex
defmodule Datjournaal.Router do
  use Datjournaal.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :with_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug Datjournaal.CurrentUser
  end

  pipeline :login_required do
    plug Guardian.Plug.EnsureAuthenticated,
         handler: Datjournaal.GuardianErrorHandler
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
  end

  scope "/", Datjournaal do
    pipe_through [:browser, :with_session]

    get "/", IndexController, :index
    resources "/sessions", SessionController, only: [:new, :create, :delete]

    scope "/" do
      pipe_through [:login_required]
      resources "/posts", ImagePostController, only: [:create, :delete, :new]
      resources "/settings", UserSettingsController, only: [:index, :delete]
      resources "/stats", UserStatsController, only: [:index]
      resources "/text_posts", TextPostController, only: [:new, :edit, :create, :delete, :update]
      get "/auth/request", TwitterAuthController, :request
      get "/auth/callback", TwitterAuthController, :callback
      get "/auth/logout", TwitterAuthController, :logout
    end
    get "/about", StaticPagesController, :about
    get "/texts/:slug", IndexController, :show_text
    get "/images/:slug", IndexController, :show_image
    get "/:slug", IndexController, :show_legacy #This has to be the last route in the file because it acts as a catch-all
  end
  # Other scopes may use custom stacks.
  scope "/api", Datjournaal do
    pipe_through [:api]
    scope "/" do
      pipe_through [:with_session]
      scope "v1" do
        pipe_through [:login_required]
        get "/location", LocationController, :get_location_for_name
      end
      scope "v1" do
        post "/visit/image/:id", TrackingController, :log_image_visit
        post "/visit/text/:id", TrackingController, :log_text_visit
      end
    end
  end
end

web/controllers/user_settings_controller.ex
defmodule Datjournaal.UserSettingsController do
  use Datjournaal.Web, :controller

  alias Datjournaal.{Repo, User, TwitterKey}

  def index(conn, _params) do
    current_user = Repo.preload(conn.assigns.current_user, :twitterkey)
    changeset = User.change_password_changeset(%{})
    render(conn, "index.html", user: current_user, changeset: changeset)
  end

  def delete(conn, %{"id" => id}) do
    key = Repo.get!(TwitterKey, id)
    Repo.delete!(key)
    conn |> redirect(to: user_settings_path(conn, :index))
  end

  def change_password(conn, params) do
    current_user = conn.assigns.current_user
    changeset = current_user |> User.change_password_changeset(params)

    case Repo.update(changeset) do
      {:ok, _user}         -> conn |> redirect(to: user_settings_path(conn, :index))
      {:error, changeset} ->
        IO.inspect changeset
        conn
        |> render("index.html", %{ changeset: changeset, user: Repo.preload(current_user, :twitterkey) })
    end
  end
end

web/templates/user_settings/index.html.eex
<div class="user-settings">
  <div class="twitter-account">
    <h1>Manage your Twitter account</h1>
    <%= if @user.twitterkey do %>
      <div>Configured account name</div>
      <div><%= @user.twitterkey.name %> - <%= @user.twitterkey.screen_name %></div>
      <%= button "Unlink Twitter account", to: user_settings_path(@conn, :delete, @user.twitterkey.id), method: :delete, class: "flat-button" %>
    <% else %>
      <%= link "Login with Twitter", to: twitter_auth_path(@conn, :request), class: "flat-button" %>
    <% end %>
  </div>
  <div class="change-password">
    <h1>Change your password</h1>
    <%= form_for @changeset, user_settings_path(@conn, :change_password), fn f -> %>
      <div class="form-group">
        <%= label f, :current_password %>
        <%= text_input f, :current_password %>
      </div>
      <div class="form-group">
        <%= label f, :new_password %>
        <%= text_input f, :new_password %>
      </div>
      <div class="form-group">
        <%= label f, :new_password_confirmation %>
        <%= text_input f, :new_password_confirmation %>
      </div>
      <div class="form-group">
        <%= submit "Change password", class: "flat-button submit" %>
      </div>
    <% end %>
  </div>
</div>